version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/harsh-browserstack/hello-world/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  machine:
    environment:
      BROWSERSTACK_USERNAME: harshpathar2
      BROWSERSTACK_ACCESS_KEY: in7ppDXRFGKRix7S6ujF
      BROWSERSTACK_LOCAL: false
      BROWSERSTACK_LOCAL_IDENTIFIER: identifier
    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          # echo Hello, World!

workflows:
  my-custom-workflow:
    jobs:
      - machine
